<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AR.aspx.cs" Inherits="Admin_AR" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<link href="AM.css" rel="stylesheet" type="text/css" />
<link href="AM2.css" rel="stylesheet" type="text/css" />
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        #Reset1
        {
            font-style: italic;
            font-weight: 700;
            text-decoration: underline;
            color: #CC0000;
            font-size: large;
            font-family: Arial;
            background-color: #CCFFFF;
        }
    </style>
    <script language="javascript" type="text/javascript">

      
    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div class=Rdiv align="middle" >
        <table class="style1">
            <tr>
                <td>
                    <div class =Rdiv2 >
                        <asp:GridView ID="GridView1" runat="server"
                            OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                            BackColor="White" BorderColor="#999999"
                            BorderStyle="Solid" BorderWidth="1px" CellPadding="2" ForeColor="Black"
                            GridLines="Vertical" Width="740px" AllowSorting="True" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" AutoGenerateColumns="False">
                            <AlternatingRowStyle BackColor="#CCCCCC" />
                            <Columns>
                                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" InsertVisible="False" SortExpression="Id"></asp:BoundField>
                                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name"></asp:BoundField>
                                <asp:BoundField DataField="Mo_number" HeaderText="Mo_number" SortExpression="Mo_number"></asp:BoundField>
                                <asp:BoundField DataField="address" HeaderText="address" SortExpression="address"></asp:BoundField>
                                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email"></asp:BoundField>
                                <asp:BoundField DataField="pincode" HeaderText="pincode" SortExpression="pincode"></asp:BoundField>
                                <asp:BoundField DataField="password" HeaderText="password" SortExpression="password"></asp:BoundField>
                          
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                            ConnectionString="<%$ ConnectionStrings:dbcs1 %>"
                            DeleteCommand="DELETE FROM [REG_table] WHERE [Id] = @original_Id"
                            InsertCommand="INSERT INTO [REG_table] ([name], [Mo_number], [address], [email], [pincode], [password]) VALUES (@name, @Mo_number, @address, @email, @pincode, @password)"
                            OldValuesParameterFormatString="original_{0}"
                            SelectCommand="SELECT * FROM [REG_table]"
                            UpdateCommand="UPDATE [REG_table] SET [name] = @name, [Mo_number] = @Mo_number, [address] = @address, [email] = @email, [pincode] = @pincode, [password] = @password WHERE [Id] = @original_Id"
                            OnSelecting="SqlDataSource1_Selecting">
                            <DeleteParameters>
                                <asp:Parameter  Name="original_Id" Type="Int32"  />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter  Name="name" Type="String" />
                                <asp:Parameter  Name="Mo_number" Type="String" />
                                <asp:Parameter  Name="address" Type="String" />
                                <asp:Parameter  Name="email" Type="String" />
                                <asp:Parameter  Name="pincode" Type="String" />
                                <asp:Parameter  Name="password" Type="String" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter  Name="name" Type="String"  />
                                <asp:Parameter  Name="Mo_number" Type="String" />
                                <asp:Parameter  Name="address" Type="String" />
                                <asp:Parameter  Name="email" Type="String" />
                                <asp:Parameter  Name="pincode" Type="String" />
                                <asp:Parameter  Name="password" Type="String" />
                                <asp:Parameter  Name="original_Id" Type="Int32"  />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                </td>
            </tr>
        </table>
        &nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="Button1" runat="server" BorderStyle="Dotted" Height="40px" 
            onclick="Button1_Click" 
            style="color: #FFFFFF; text-decoration: underline; font-style: italic; font-weight: 700; font-size: large; font-family: 'Arial Black'; background-color: #3333FF" 
            Text="Privious" Width="150px" />
    </div>
    </div>
    </form>
</body>
</html>
